name: Build
on: [push]
jobs:
  Build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install autoconf automake bison pkg-config boost

      - name: Boostrap
        run: ./bootstrap.sh

      - name: Configure
        run: ./configure

      - name: Make
        run: make

      - uses: actions/upload-artifact@v3
        with:
          name: thrift
          path: ./thrift
