name: Build
on: [push]
jobs:
  Build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install autoconf automake bison@2.7 pkg-config boost libtool

      - name: Update PATH
        run: |
          echo 'export PATH="/opt/homebrew/opt/bison@2.7/bin:$PATH"' >> /Users/runner/.bash_profile
          export LDFLAGS="-L/opt/homebrew/opt/bison@2.7/lib"

      - name: Boostrap
        run: ./bootstrap.sh

      - name: Configure
        run: |
          export CFLAGS="-Wno-deprecated-copy-with-user-provided-copy"
          export CXXFLAGS="-Wno-deprecated-copy-with-user-provided-copy"

          ./configure

      - name: Make
        run: |
          export CFLAGS="-Wno-deprecated-copy-with-user-provided-copy"
          export CXXFLAGS="-Wno-deprecated-copy-with-user-provided-copy"

          cd ./compiler/cpp
          make

      - name: Add executable permission
        run: chmod +x ./compiler/cpp/thrift

      - name: 'Zip files'
        run: zip -j ./thrift.zip ./compiler/cpp/thrift

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: thrift.zip
          path: ./thrift.zip
